---
- name: my first playbook
  hosts: all
  become: true

  vars:
     service: nginx

  tasks:
   - name: to install nginx and to start the server
     ansible.builtin.apt:
       name: "{{ service }}"
       state: present
   - name: to start the nginx service
     ansible.builtin.service:
       name: "{{ service }}"
       state: started
       enabled: true
