---
- name: to install mutiple pacakges on all the servers
  hosts: all
  become: yes
  tasks:
  - name: to install common pacakges like wget,curl,git,htop
    ansible.builtin.apt: 
      name:
       - git
       - curl 
       - apache2
       - wget
       - htop
      state: present
      update_cache: yes
  